[tasks.wasm]
install_crate = "wasm-pack"
command = "wasm-pack"
args = ["build"]

[tasks.wasm-server]
script=[
'''
cd ./www
npm run start
'''
]

[tasks.server]
dependencies = ["wasm","wasm-server"]

[tasks.build]

[tasks.init_www]
script=[
'''
npm init wasm-app www
cd ./pkg
npm link
cd ..
cd ./www
npm link ${CARGO_MAKE_CRATE_NAME}
'''
]
dependencies = ["wasm"]
